Deprecate NIRSpec workarounds
spacetelescope/jwst-caveat-examples pull request #17
Opened 2024-02-28 15:54 UTC by melanieclarke

Adding deprecation notes for extraction recentering, S200A1/2 combination, and missing error workarounds.

2024-03-01 18:00 UTC, sosey requested changes
Had some minor comments for 2 of the notebooks

2024-03-01 18:00 UTC, sosey commented on NIRSPEC_General/nrs_missing_spectral_error_workaround.ipynb
@melanieclarke in this one, I had to change the name of the example file to get something that existed in MAST: 

> spec3_name = 'jw01128-o007_s00001_nirspec_f170lp-g235h-s200a2-subs200a2'

2024-03-01 18:02 UTC, sosey commented
@drlaw1558 has the JDOX table been updated for the deprecations here?

2024-03-06 17:37 UTC, drlaw1558 commented
I've noted these deprecations as such in the D2P table.  Going forward, the NIRSpec team should update the JDox known issues tables accordingly when notebooks are deprecated.

2024-03-11 16:57 UTC, melanieclarke commented on NIRSPEC_General/nrs_missing_spectral_error_workaround.ipynb
Fixed.

2024-03-11 16:58 UTC, melanieclarke commented on NIRSPEC_Fixed_Slit/nrs_fss_s200a1_s200a2_workaround.ipynb
Thanks for pointing this out.  I added a note at the top about the pipeline version and context used at the time of writing, and modified the two cells at the bottom to work for either current or old pipeline naming system.  Let me know if you think it needs more clarification.

2024-03-11 17:47 UTC, sosey approved these changes

2024-04-26 18:48 UTC, merged